### ISSUE TITLE
refactor(server/docker-compose.yml): specify tag

### ISSUE THREAD

**Issue by jjangga0214** [kookmin-sw/capstone-2020-12#141]
https://github.com/kookmin-sw/capstone-2020-12/blob/d6996d708c9dce6c233a75b5b73c86f5288a8589/src/server/docker-compose.yml#L17-L18

어차피 docker-compose 를 개발용으로 사용하죠. 그래서 컨테이너를 외부로부터 격리시키는게 의미가 없습니다.

예를 들어, production 에서는 db가 사설망에서만 접근가능해 인터넷으로부터의 엑세스를 원천 차단하는게 best practice 죠.

그렇지만 개발시에는 직접 db 에 접속하고 싶은 상황이 생기기도 합니다. 

그래서 `ports.mode` 를 `host` 로 설정하는 게 좋다고 생각합니다.

그리고 이렇게 하면 만약에 어떤 멤버의 컴퓨터에서 5432 포트가 이미 점유중인 경우 곤란하겠죠.

그러므로 포트도 환경변수로 (.env.local 등에 명시되어 있겠죠?) 설정하면 좋겠죠.

```yaml
services:
  db:
    ports:
      - target: 5432
        published: ${POSTGRES_ENDPOINT_PORT}
        protocol: tcp
        mode: host
```
