### ISSUE TITLE
refactor(server/docker-compose.yml): use named volume

### ISSUE THREAD

**Issue by jjangga0214** [kookmin-sw/capstone-2020-12#142]
https://github.com/kookmin-sw/capstone-2020-12/blob/d6996d708c9dce6c233a75b5b73c86f5288a8589/src/server/docker-compose.yml#L20

특수한 이유가 없다면 절대경로나 상대경로를 명시하는 대신 추상화된 named volume 을 쓰는게 좋다고 생각합니다.

이렇게요~ 

```yaml
services:
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
```
